tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

brew 'coreutils'
brew 'bash'
brew 'grep'
brew 'tree'
brew 'fzf'
brew 'direnv'
brew 'z'
brew 'ansible'
brew 'glide'
brew 'postgres'
brew 'docker'
brew 'docker-compose'
brew 'dlite'
brew 'nginx'
brew 'wget'
brew 'pow'
brew 'redis'
brew 'memcached'
brew 'the_silver_searcher'
brew 'hub'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'ctags'
brew 'htop'

# Programming languages
brew 'lua'
brew 'luajit'
brew 'python3'

brew 'vim', args: ['override-system-vi', 'luajit', 'lua', 'python3']
brew 'go'
brew 'node'

brew 'rbenv'
brew 'ruby-build'

brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'

brew 'carthage'

brew 'elixir'
brew 'elm'
brew 'curl'
brew 'exercism'

# tools
brew 'switchaudio-osx'
brew 'axel'
brew 'lesspipe'
brew 'unison'
brew 'unrar'
brew 'xz'
brew 'ssh-copy-id'
brew 'zeromq'


cask_args appdir: '/Applications'

# General
cask '1password'
cask 'alfred'
cask 'vlc'
cask 'dropbox'
cask 'google-chrome'
cask 'mumble'
cask 'nicecast'
cask 'omnifocus'
cask 'omnigraffle'
cask 'rstudio'
cask 'skype'
cask 'sonos'
cask 'spotify'
cask 'sketch'

# UI
cask 'flux'
cask 'inkscape'

# Utilities
cask 'paw'
cask 'little-snitch'
cask 'audio-hijack'
cask 'geektool'
cask 'licecap'
cask 'hammerspoon'
cask 'bartender'
cask 'handbrake'
cask 'karabiner'
cask 'bitbar'

# Added Quicklook addons
cask 'betterzipql'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'bitbar'
cask 'licecap'
cask 'qlimagesize'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'soundcloud-downloader'
cask 'webpquicklook'

# Development
cask 'iterm2'
cask 'atom'
cask 'vagrant'
cask 'virtualbox'
cask 'gitup'
cask 'font-hack'
cask 'postgres'
cask 'postico'
cask 'mactex'
